"""initial schema — all tables

Revision ID: 1ee28eb6f71e
Revises: 
Create Date: 2026-02-23 09:58:07.322710
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ee28eb6f71e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendees_email'), 'attendees', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_creators',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_co_creators_email'), 'co_creators', ['email'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('pricing_model', sa.Enum('fixed', 'donation', 'free', name='pricingmodel', native_enum=False), nullable=False),
    sa.Column('fixed_price_cents', sa.Integer(), nullable=True),
    sa.Column('min_donation_cents', sa.Integer(), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('meeting_point_a', sa.Text(), nullable=True),
    sa.Column('meeting_point_b', sa.Text(), nullable=True),
    sa.Column('reminder_delay_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_expire_hours', sa.Integer(), nullable=False),
    sa.Column('day_of_sms_time', sa.Time(), nullable=True),
    sa.Column('registration_fields', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('notification_templates', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'cancelled', name='eventstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', name='userrole', native_enum=False), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('webhooks_raw',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooks_raw_stripe_event_id'), 'webhooks_raw', ['stripe_event_id'], unique=True)
    op.create_table('event_co_creators',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('co_creator_id', sa.Uuid(), nullable=False),
    sa.Column('can_see_amounts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['co_creator_id'], ['co_creators.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'co_creator_id')
    )
    op.create_table('registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attendee_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'complete', 'expired', 'cancelled', 'refunded', name='registrationstatus', native_enum=False), nullable=False),
    sa.Column('payment_amount_cents', sa.Integer(), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('accommodation_type', sa.Enum('bell_tent', 'nylon_tent', 'self_camping', 'yurt_shared', 'none', name='accommodationtype', native_enum=False), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('intake_data', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('waiver_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('registration_form', 'manual', 'walk_in', name='registrationsource', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendees.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendee_id', 'event_id', name='uq_attendee_event')
    )
    op.create_index(op.f('ix_registrations_attendee_id'), 'registrations', ['attendee_id'], unique=False)
    op.create_index(op.f('ix_registrations_event_id'), 'registrations', ['event_id'], unique=False)
    op.create_table('notifications_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', name='notificationchannel', native_enum=False), nullable=False),
    sa.Column('template_id', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', 'bounced', name='notificationstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_registration_id'), 'notifications_log', ['registration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_log_registration_id'), table_name='notifications_log')
    op.drop_table('notifications_log')
    op.drop_index(op.f('ix_registrations_event_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_attendee_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_table('event_co_creators')
    op.drop_index(op.f('ix_webhooks_raw_stripe_event_id'), table_name='webhooks_raw')
    op.drop_table('webhooks_raw')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_co_creators_email'), table_name='co_creators')
    op.drop_table('co_creators')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_attendees_email'), table_name='attendees')
    op.drop_table('attendees')
    # ### end Alembic commands ###
